services:
  bot:
    build: .
    container_name: 3xui-tg-client-pay
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - ADMIN_PANEL_PASSWORD=${ADMIN_PANEL_PASSWORD:-}
      - ENABLE_CODE_EDITOR=${ENABLE_CODE_EDITOR:-false}
